# golangci-lint configuration for Tide API

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - gocritic
    - revive
    - misspell
    - unparam
    - prealloc
    - unconvert
    - nakedret
    - noctx
    - gochecknoinits
    - gochecknoglobals
    - exhaustive
    - godot
    - nestif
    - copyloopvar
    - goconst
    - gocyclo
    - dupl

  settings:
    govet:
      disable:
        - shadow

    errcheck:
      check-type-assertions: true
      check-blank: false

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - commentedOutCode
        - equalFold

    revive:
      confidence: 0.8

    godot:
      scope: declarations
      capital: false

    nestif:
      min-complexity: 5

    gosec:
      excludes:
        - G104
        - G115
        - G304
        - G204
        - G301
        - G306

    goconst:
      min-len: 3
      min-occurrences: 3

    gocyclo:
      min-complexity: 27

    dupl:
      threshold: 150

    nakedret:
      max-func-lines: 30

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
